application: noisemakerclub # Change this to the unique name for your new app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /newcomment.*
  script: comment.app

- url: /comment.*
  script: comment.app

- url: /vote.*
  script: vote.app

- url: /newest.*
  script: newest.app

- url: /item.*
  script: item.app

- url: /submit.*
  script: item.app

- url: /zf.*
  script: jobs.app

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: django
  version: "1.4"